# Constants for GB80 - Grandpa BASIC 1980

# The largest signed 16-bit integer, standard for old BASIC interpreters.
MAX_LINE_NUMBER = 32767

HELP_MESSAGE = (
    'LIST - LIST THE PROGRAM LINES',
    'CLEAR - REMOVE ALL PROGRAM LINES',
    'TO REMOVE A SINGLE PROGRAM LINE, TYPE THE LINE NUMBER AND PRESS <ENTER>',
    'RUN - RUN THE PROGRAM',
    'SAVE "ABC" - SAVE THE GB80 PROGRAM LOCALLY, WITH THE FILENAME ABC.GB80,',
    'WHERE "ABC" REPRESENTS A STRING OF 1 TO 8 ALPHANUMERIC CHARACTERS',
    'FILES - LIST SAVED GB80 PROGRAM FILES',
    'HELP - DISPLAY THIS HELP MESSAGE',
)
